---
zabbix:
  user: zabbix_api_user
  pass: StrongSecretPa$$
  server: https://zabbix.example.com

cachet:
  token: TokenFromCachet
  server: https://cachet.example.com

settings:
  # IT Service which will be a root for Cachet Components
  # Leave it empty if you want to use /
  root_service: 'Status Page'
  # How often check Zabbix for new incidents
  update_inc_interval: 120  # in seconds
  # How often check Zabbix for new IT Services
  update_comp_interval: 3600  # in seconds
  # Log level https://docs.python.org/3.4/library/logging.html#levels
  log_level: INFO
  # Additional logging level for requests module
  log_level_requests: WARNING